# This playbook retrieves system configuration of all Palo Alto firewalls
# It connects to all hosts defined in the inventory
# and uses the panos_facts module to gather all configuration.
---
- name: Get Palo Alto Networks Firewalls Session Information
  hosts: all
  connection:  local
  gather_facts:  False

  collections:
    - paloaltonetworks.panos

# Load variables from an external file
  tasks:
  - name: Load Variables
    include_vars: device_details_file.yml

  # Retrieve Full configuration from each firewall and store in register called result
  - name: Get Firewall system configuration
    panos_facts:
      provider: '{{device_details}}' # provider is one of the providers, device_details is a variable defined in vars.yml
      gather_subset: ['system'] # system is a Parameters to gather system subsets of information
    register: system_config
  
  # Display the hostname of the firewall
  - debug:
      msg: '{{system_config}}'
...