---
- name: Get Palo Alto Networks Firewalls Session Information
  hosts: all
  connection:  local
  gather_facts:  False

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Load Variables
    include_vars: vars.yml

  - name: Get the session statistic for each firewall
    panos_facts:
      provider: '{{provider}}'
      gather_subset: ['session']
    register: result

  - debug:
      msg: '{{"inventory_hostname"}} : {{ result.ansible_facts.ansible_net_session_usage }} / {{ result.ansible_facts.ansible_net_session_max }}'
...