# this playbook removes (deletes) bulk address object 
# (address object should not be used any where eaither address group or policy) 
# using loop as you can see below

---
- name: Create address object in Device Group
  hosts: panorama
  connection: local
  gather_facts: no
  collections:
    - paloaltonetworks.panos
  tasks:
    - name: remove the address object
      paloaltonetworks.panos.panos_address_object:
        provider: '{{ provider }}'
        device_group: 'BW-ISS'
        name: "{{item}}"
        state: absent
      loop:
        - one
        - 1.1.1.1
        - address_object_1
        - address_object_2
        - address_object_3
        - address_object_4
        - address_object_5
        - address_object_6
        - address_object_7
        - address_object_8
        - address_object_9
        - address_object_10
...