---
- name: Create address object in Device Group
  hosts: panorama
  connection: local
  gather_facts: no
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Get all address groups and their config
      paloaltonetworks.panos.panos_address_group:
        provider: "{{ provider }}"
        device_group: 'BW-ISS'
        state: "gathered"
        gathered_filter: "*"
      register: allgroups

    - name: Remove address object from all groups
      paloaltonetworks.panos.panos_address_group:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        device_group: 'BW-ISS'
        description: "{{ item.description | default(omit, true) }}"
  
        static_value: "{{ item.static_value | difference([rmadr]) }}"
      loop: "{{ allgroups.gathered }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.static_value
        - rmadr in item.static_value

    - name: Remove the address object
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        device_group: 'BW-ISS'
        name: "{{ rmadr }}"
        state: "absent"