---
- name: get CDP neighbour
  hosts: all
  gather_facts: false
  tasks:
    - name: show cdp neighbor
      raw: "show cdp neighbor"
      register: print_output
    - debug: var=print_output.stdout_lines