# Gather IOS facts
- name: Gather IOS facts
  hosts: all
  tasks:
    - name: Collect IOS facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Gather only the config and default facts
      cisco.ios.ios_facts:
        gather_subset:
          - config