- name: Add static route on remote Linux machine
  hosts: all
  become: yes  # Run as sudo
  tasks:
    - name: Add a route using the ip route command
      command: sudo ip route add 10.10.10.0/24 via 192.168.1.1